/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SeriesIndexImport } from './routes/series/index'
import { Route as SearchIndexImport } from './routes/search/index'
import { Route as MoviesIndexImport } from './routes/movies/index'
import { Route as SeriesSerieIDImport } from './routes/series/$serieID'
import { Route as MoviesMovieIDImport } from './routes/movies/$movieID'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SeriesIndexRoute = SeriesIndexImport.update({
  path: '/series/',
  getParentRoute: () => rootRoute,
} as any)

const SearchIndexRoute = SearchIndexImport.update({
  path: '/search/',
  getParentRoute: () => rootRoute,
} as any)

const MoviesIndexRoute = MoviesIndexImport.update({
  path: '/movies/',
  getParentRoute: () => rootRoute,
} as any)

const SeriesSerieIDRoute = SeriesSerieIDImport.update({
  path: '/series/$serieID',
  getParentRoute: () => rootRoute,
} as any)

const MoviesMovieIDRoute = MoviesMovieIDImport.update({
  path: '/movies/$movieID',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/movies/$movieID': {
      preLoaderRoute: typeof MoviesMovieIDImport
      parentRoute: typeof rootRoute
    }
    '/series/$serieID': {
      preLoaderRoute: typeof SeriesSerieIDImport
      parentRoute: typeof rootRoute
    }
    '/movies/': {
      preLoaderRoute: typeof MoviesIndexImport
      parentRoute: typeof rootRoute
    }
    '/search/': {
      preLoaderRoute: typeof SearchIndexImport
      parentRoute: typeof rootRoute
    }
    '/series/': {
      preLoaderRoute: typeof SeriesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  MoviesMovieIDRoute,
  SeriesSerieIDRoute,
  MoviesIndexRoute,
  SearchIndexRoute,
  SeriesIndexRoute,
])

/* prettier-ignore-end */
